/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewIndexRouteImport } from './routes/crew/index'
import { Route as CrewIdRouteImport } from './routes/crew/$id'
import { Route as ArticlesChar123PageChar125RouteImport } from './routes/articles/{-$page}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIdRoute = CrewIdRouteImport.update({
  id: '/crew/$id',
  path: '/crew/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesChar123PageChar125Route =
  ArticlesChar123PageChar125RouteImport.update({
    id: '/articles/{-$page}',
    path: '/articles/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/{-$page}': typeof ArticlesChar123PageChar125Route
  '/crew/$id': typeof CrewIdRoute
  '/crew': typeof CrewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/{-$page}': typeof ArticlesChar123PageChar125Route
  '/crew/$id': typeof CrewIdRoute
  '/crew': typeof CrewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/{-$page}': typeof ArticlesChar123PageChar125Route
  '/crew/$id': typeof CrewIdRoute
  '/crew/': typeof CrewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/articles/{-$page}' | '/crew/$id' | '/crew'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/articles/{-$page}' | '/crew/$id' | '/crew'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles/{-$page}'
    | '/crew/$id'
    | '/crew/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesChar123PageChar125Route: typeof ArticlesChar123PageChar125Route
  CrewIdRoute: typeof CrewIdRoute
  CrewIndexRoute: typeof CrewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/$id': {
      id: '/crew/$id'
      path: '/crew/$id'
      fullPath: '/crew/$id'
      preLoaderRoute: typeof CrewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/{-$page}': {
      id: '/articles/{-$page}'
      path: '/articles/{-$page}'
      fullPath: '/articles/{-$page}'
      preLoaderRoute: typeof ArticlesChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesChar123PageChar125Route: ArticlesChar123PageChar125Route,
  CrewIdRoute: CrewIdRoute,
  CrewIndexRoute: CrewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
